### ISSUE TITLE
Postgres Connection Pool Should have SSL Enabled

### ISSUE THREAD

**Issue by ankurdotcom** [gtmsoftware/fleet-wise#4]
const dbConnectionPool = new Pool({
...
  idleTimeoutMillis: process.env.DB_IDLE_TIMEOUT_MS,
  connectionTimeoutMillis: process.env.DB_CONNECTION_TIMEOUT_MS,
  **ssl: {  rejectUnauthorized: false },** 
});

**Comment by dev-ambar** [comment]
Assign me

**Comment by gtmsoftware** [comment]
assigned to @dev-ambar
